// flow-typed signature: b713bbc58a4ecd52bcd945f86f95ef86
// flow-typed version: <<STUB>>/@workpop/eslint-config-workpop_v^0.0.8/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@workpop/eslint-config-workpop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@workpop/eslint-config-workpop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@workpop/eslint-config-workpop/config/es6' {
  declare module.exports: any;
}

declare module '@workpop/eslint-config-workpop/config/flow' {
  declare module.exports: any;
}

declare module '@workpop/eslint-config-workpop/config/globals' {
  declare module.exports: any;
}

declare module '@workpop/eslint-config-workpop/config/opinions' {
  declare module.exports: any;
}

declare module '@workpop/eslint-config-workpop/config/react' {
  declare module.exports: any;
}

// Filename aliases
declare module '@workpop/eslint-config-workpop/config/es6.js' {
  declare module.exports: $Exports<'@workpop/eslint-config-workpop/config/es6'>;
}
declare module '@workpop/eslint-config-workpop/config/flow.js' {
  declare module.exports: $Exports<'@workpop/eslint-config-workpop/config/flow'>;
}
declare module '@workpop/eslint-config-workpop/config/globals.js' {
  declare module.exports: $Exports<'@workpop/eslint-config-workpop/config/globals'>;
}
declare module '@workpop/eslint-config-workpop/config/opinions.js' {
  declare module.exports: $Exports<'@workpop/eslint-config-workpop/config/opinions'>;
}
declare module '@workpop/eslint-config-workpop/config/react.js' {
  declare module.exports: $Exports<'@workpop/eslint-config-workpop/config/react'>;
}
declare module '@workpop/eslint-config-workpop/index' {
  declare module.exports: $Exports<'@workpop/eslint-config-workpop'>;
}
declare module '@workpop/eslint-config-workpop/index.js' {
  declare module.exports: $Exports<'@workpop/eslint-config-workpop'>;
}
